name: Merge Widgets

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'repo/repo.json'
      - '.github/scripts/**'
      - '.github/workflows/**'
  schedule:
    - cron: "0 3,18 * * *"

jobs:
  merge:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      - name: Install dependencies
        run: pip install requests packaging

      - name: Run merge script
        run: python .github/scripts/merge.py

      - name: Commit and push changes
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add allinone.fwd README.md
          git commit -m "🤖 Auto update allInOne.fwd and README.md [skip ci]" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}